# Generated by Django 5.2.8 on 2025-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Image de profil de l'utilisateur. Stockée dans le dossier 'avatars/'.", null=True, upload_to='avatars/', verbose_name='Avatar / Photo de profil'),
        ),
    ]
