# Generated by Django 5.2.8 on 2025-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email & Password'), ('google', 'Google OAuth')], default='email', help_text="Méthode utilisée par l'utilisateur pour créer son compte.", max_length=20, verbose_name="Méthode d'enregistrement"),
        ),
    ]
