# Generated by Django 5.2.8 on 2025-11-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date', 'order'], 'verbose_name': 'Expérience', 'verbose_name_plural': 'Expériences'},
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tâches et Réalisations'),
        ),
    ]
